# Generated by Django 5.1.3 on 2024-12-01 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='KUKU', max_length=50, verbose_name='Article_title')),
                ('anons', models.CharField(default='ZUZU', max_length=250, verbose_name='Announcement')),
                ('full_text', models.TextField(verbose_name='Article')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
